export const ROLES = {
  3: ["spy", "resistance", "resistance"],
  4: ["spy", "resistance", "resistance", "resistance"],
  5: ["spy", "spy", "resistance", "resistance", "resistance"],
  6: ["spy", "spy", "resistance", "resistance", "resistance", "resistance"],
  7: [
    "spy",
    "spy",
    "spy",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
  ],
  8: [
    "spy",
    "spy",
    "spy",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
  ],
  8: [
    "spy",
    "spy",
    "spy",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
  ],
  10: [
    "spy",
    "spy",
    "spy",
    "spy",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
    "resistance",
  ],
};
